apiVersion: v1
kind: Secret
metadata:
  name: cactus-house-backend-secrets
type: Opaque
data:           
  DB_USER: Y2FjdHVzdXNlcg==     
  DB_PASSWORD: Y2FjdHVzcGFzcw== 
  DB_NAME: Y2FjdHVzX2hvdXNl 
---
apiVersion: v1
kind: Service
metadata:
  name: cactus-house-backend
spec:
  type: NodePort
  selector:
    app: cactus-house-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 5000 
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cactus-house-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cactus-house-backend
  template:
    metadata:
      labels:
        app: cactus-house-backend
    spec:
      containers:
        - name: cactus-house-backend
          image: thimira97/cactus_house_api:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cactus-house-backend-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cactus-house-backend-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cactus-house-backend-secrets
                  key: DB_NAME